
AWSTemplateFormatVersion: "2010-09-09"
Description: Resume Site infra - S3 (versioned), DynamoDB (DeploymentTracking, ResumeAnalytics), optional OIDC role.

Parameters:
  BucketName:
    Type: String
    Description: Name for the public, versioned S3 bucket hosting the resume site.
  ProjectTag:
    Type: String
    Default: resume-site
    Description: Tag value to group resources.

Resources:
  ResumeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
        - Key: project
          Value: !Ref ProjectTag

  ResumeBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ResumeBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # Public read of site files (index.html, css, etc.)
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource:
              - !Sub arn:aws:s3:::${ResumeBucket}/beta/*
              - !Sub arn:aws:s3:::${ResumeBucket}/prod/*

  DeploymentTrackingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectTag}-DeploymentTracking"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: commit_sha
          AttributeType: S
        - AttributeName: env_ts
          AttributeType: S
      KeySchema:
        - AttributeName: commit_sha
          KeyType: HASH
        - AttributeName: env_ts
          KeyType: RANGE
      Tags:
        - Key: project
          Value: !Ref ProjectTag

  ResumeAnalyticsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectTag}-ResumeAnalytics"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: commit_sha
          AttributeType: S
        - AttributeName: analysis_key
          AttributeType: S
      KeySchema:
        - AttributeName: commit_sha
          KeyType: HASH
        - AttributeName: analysis_key
          KeyType: RANGE
      Tags:
        - Key: project
          Value: !Ref ProjectTag

  # OPTIONAL: set up GitHub OIDC so Actions can assume a role without long-lived keys.
  # Comment out this block if you will use plain AWS keys in GitHub Secrets.
  GitHubOidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1  # GitHub OIDC thumbprint

  ResumeCiCdRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectTag}-cicd-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOidcProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: "repo:<YOUR_GH_OWNER>/<YOUR_REPO>:*"
      Policies:
        - PolicyName: s3-ddb-cfn-access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:CopyObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${ResumeBucket}
                  - !Sub arn:aws:s3:::${ResumeBucket}/*
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DescribeTable
                Resource:
                  - !GetAtt DeploymentTrackingTable.Arn
                  - !GetAtt ResumeAnalyticsTable.Arn
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:GetTemplate
                Resource: "*"
      Tags:
        - Key: project
          Value: !Ref ProjectTag

Outputs:
  OutBucketName:
    Value: !Ref ResumeBucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"
  OutDeployTable:
    Value: !Ref DeploymentTrackingTable
  OutAnalyticsTable:
    Value: !Ref ResumeAnalyticsTable
  OutCiCdRoleArn:
    Value: !GetAtt ResumeCiCdRole.Arn