
name: Analyze images on PR (beta)

on:
  pull_request:
    branches: ["main"]

jobs:
  upload-beta-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload images to S3 (beta)
        shell: bash
        run: |
          shopt -s nullglob
          for f in images/*.jpg images/*.jpeg images/*.png; do
            base="$(basename "$f")"
            aws s3 cp "$f" "s3://${{ secrets.S3_BUCKET }}/rekognition-input/beta/${base%.*}-$(date +%s).${base##*.}"
          done
